# symbols.py
# Updated and cleaned list of BIST symbols (approx BIST 100 constituents)
# Standardized to unique tickers with .IS suffix for Yahoo Finance.

BIST_SYMBOLS = [
    "ACSEL.IS", "ADEL.IS", "AESOT.IS", "AFYON.IS", "AGESA.IS", "AGHOL.IS", "AKBNK.IS", 
    "AKCNS.IS", "AKFGY.IS", "AKFYE.IS", "AKGRT.IS", "AKMGY.IS", "AKSA.IS", "AKSEN.IS", 
    "ALARK.IS", "ALBRK.IS", "ALCTL.IS", "ALGYO.IS", "ALKA.IS", "ALKIM.IS", "ANELE.IS", 
    "ANGEN.IS", "ANHYT.IS", "ANSGR.IS", "ARCLK.IS", "ARDYZ.IS", "ARENA.IS", "ARSAN.IS", 
    "ARZUM.IS", "ASELS.IS", "ASUZU.IS", "AYDEM.IS", "AYGAZ.IS", "BAGFS.IS", "BAKAB.IS", 
    "BANVT.IS", "BERA.IS", "BEYAZ.IS", "BIMAS.IS", "BIOEN.IS", "BIZIM.IS", "BJKAS.IS", 
    "BLCYT.IS", "BRISA.IS", "BRKSN.IS", "BRSAN.IS", "BRYAT.IS", "BUCIM.IS", "CANTE.IS", 
    "CCOLA.IS", "CEMAS.IS", "CEMTS.IS", "CIMSA.IS", "CONSE.IS", "CWENE.IS", "DAGI.IS", 
    "DEVA.IS", "DITAŞ.IS", "DMSAS.IS", "DOAS.IS", "DOHOL.IS", "DPNTR.IS", "DYOBY.IS", 
    "EBEBK.IS", "ECILC.IS", "ECZYT.IS", "EGEEN.IS", "EGGUB.IS", "EGSER.IS", "EKGYO.IS", 
    "ENJSA.IS", "ENKAI.IS", "ERCB.IS", "EREGL.IS", "ESEN.IS", "EUPWR.IS", "FROTO.IS", 
    "GARAN.IS", "GENIL.IS", "GEREL.IS", "GESAN.IS", "GLYHO.IS", "GOZDE.IS", "GSDHO.IS", 
    "GUBRF.IS", "GWIND.IS", "HALKB.IS", "HEKTS.IS", "HTTBT.IS", "HUBVC.IS", "HUNER.IS", 
    "IEYHO.IS", "IHLAS.IS", "IHLGM.IS", "INDES.IS", "INVEO.IS", "IPEKE.IS", "ISCTR.IS", 
    "ISDMR.IS", "ISFIN.IS", "ISGYO.IS", "ISMEN.IS", "IZMDC.IS", "KARDM.IS", "KARDD.IS", 
    "KAREL.IS", "KARSN.IS", "KARTN.IS", "KCHOL.IS", "KMPUR.IS", "KONTR.IS", "KONYA.IS", 
    "KORDS.IS", "KOZAA.IS", "KOZAL.IS", "KRDMA.IS", "KRDMB.IS", "KRDMD.IS", "KRONT.IS", 
    "KRVGD.IS", "KZBGY.IS", "MAVI.IS", "MGROS.IS", "MIATK.IS", "MPARK.IS", "MSGYO.IS", 
    "NETAS.IS", "NTHOL.IS", "NUGYO.IS", "ODAS.IS", "OTKAR.IS", "OYAKC.IS", "PARSN.IS", 
    "PEKGY.IS", "PENTA.IS", "PETKM.IS", "PGSUS.IS", "PNLSN.IS", "QUAGR.IS", "SAHOL.IS", 
    "SASA.IS", "SAYAS.IS", "SDTTR.IS", "SELEC.IS", "SISE.IS", "SKBNK.IS", "SMRTG.IS", 
    "SNGYO.IS", "SOKM.IS", "TAVHL.IS", "TCELL.IS", "THYAO.IS", "TKFEN.IS", "TKNSA.IS", 
    "TMSN.IS", "TOASO.IS", "TRGYO.IS", "TSKB.IS", "TSPDR.IS", "TUPRS.IS", "TURSG.IS", 
    "ULKER.IS", "VAKBN.IS", "VESBE.IS", "VESTL.IS", "YEOTK.IS", "YKBNK.IS", "YYLGD.IS", 
    "ZOREN.IS"
]